README.md

change 1 word

---

doc/feeds.md

typo, no clocks here

---

contrib/templates/default/postform.mustache

Fix input file size in new post page

---

contrib/static/site.css
contrib/templates/default/frontpage.mustache
contrib/templates/default/graph_history.mustache

-background color bleeds through graph
-spacing between graphs on fp

graph bleed-through, add spacing

---

contrib/templates/default/post.mustache

tbh smh onii-fam
also figcaption is completely unnecessary here tbh.

target="_blank" needs to be after href or it no werk

---

contrib/static/site.css
contrib/templates/default/board.mustache
contrib/templates/default/catalog.mustache

Styling has to be done properly, because I just stole it from Lynx to have something at least.

Add catalog

---

.gitignore
contrib/static/site.css
contrib/templates/default/board.mustache
contrib/templates/default/boardlist.mustache
contrib/templates/default/catalog.mustache
contrib/templates/default/frontpage.mustache
contrib/templates/default/graph_history.mustache
contrib/templates/default/keygen.mustache
contrib/templates/default/modlogin.mustache
contrib/templates/default/modlogin_result.mustache
contrib/templates/default/modpage.mustache
contrib/templates/default/navbar.mustache
contrib/templates/default/newboard.mustache
contrib/templates/default/overview.mustache
contrib/templates/default/post.mustache
contrib/templates/default/post_fail.mustache
contrib/templates/default/post_retry.mustache
contrib/templates/default/post_success.mustache
contrib/templates/default/postform.mustache
contrib/templates/default/posts_graph.mustache
contrib/templates/default/thread.mustache
contrib/templates/default/ukko.mustache
contrib/translations/de-DE.ini
contrib/translations/en-US.ini

I'll add documentation for this too. The strings in the daemon still have to be localized.

Add internationalization

---

contrib/templates/default/inst_api.mustache
contrib/templates/default/inst_bins.mustache
contrib/templates/default/inst_cache.mustache
contrib/templates/default/inst_crypto.mustache
contrib/templates/default/inst_db.mustache
contrib/templates/default/inst_frontend.mustache
contrib/templates/default/inst_key.mustache
contrib/templates/default/inst_nntp.mustache
contrib/templates/default/inst_postgres_db.mustache
contrib/templates/default/inst_redis_cache.mustache
contrib/templates/default/inst_redis_db.mustache
contrib/translations/en-US.ini

Add installer

---

contrib/static/site.css
contrib/templates/default/postform.mustache

this has been annoying me for a while now.

make postform more compact

---

contrib/static/site.css
contrib/templates/default/post.mustache
contrib/translations/en-US.ini

>yfw when it's this easy and it's still broken on 8chan

 add download link for files with original filename

---

doc/debian8.5-step-by-step.md

This will help users with a step-by-step guide to installing nntpchan and all of its components. I will try to make this into a script or something one day.

Step-by-step for Debian 8.5

---

doc/srnd.md

I have 40% confidence this is correct :v)

update definitions for allow_anon*

---

doc/building-debian8.5.md

redis is trash kill you'reself

deprecate redis

---

contrib/templates/default/postform.mustache

Now less bean jumping and more meme having.

set explicit height and width for captcha

---

contrib/backends/srndv2/src/srnd/nntp.go

some NNTP improvements

---

contrib/backends/srndv2/src/srnd/nntp.go

this should fix mirroring of SRNd

specify correct range in XOVER when mirroring

---

contrib/backends/srndv2/src/srnd/nntp.go

original PR was trash tbh. sorry lol

small insignificant fix

---

contrib/backends/srndv2/src/srnd/nntp.go

Yes, I'm aware it sometimes may still return wrong code.

fix ARTICLE not returning any error

---

contrib/backends/srndv2/src/srnd/util.go

This axes out literally insane overly restrictive regex-based
Message-ID check and replaces it with clean and simple conditions
specified in RFC 3977.
Old check wasn't compliant with any email or netnews internet
standard I know of, and was causing propagation issues.
Even old RFC 822 (email) and RFC 850 (usenet) specifications
don't have so restrictive specifications.

srnd: more lax Message-ID check

---

contrib/backends/srndv2/src/srnd/store.go
contrib/backends/srndv2/src/srnd/util.go

it didn't properly propagate error if connection suddenly died while transferring message.
this should fix that.

srnd: error while reading message isn't valid thing

---

contrib/backends/srndv2/src/srnd/util.go

changes unicode range to same thing my stuff uses (I like consistency).
makes it actually use utf-8, also adds variant character to force chars be monochrome.
also uses strings.builder as that's much better than repeatedly concatenating strings.

srnd: change unicode tripcode rune range

---

contrib/backends/srndv2/src/srnd/attachment.go
contrib/js/nntpchan/livechan.js

remove redundant words in comment

chore: remove redundant words in comment
